//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int UserId { get; set; }
        public int PropertyId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual User User { get; set; }
    }
}
