//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAttribute
    {
        public Nullable<int> PropertyId { get; set; }
        public string key { get; set; }
        public string value { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
