//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Token { get; set; }
        public System.DateTime Expires { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    
        public virtual User User { get; set; }
    }
}
