//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urban()
        {
            this.Properties = new HashSet<Property>();
            this.UrbanAttributes = new HashSet<UrbanAttribute>();
            this.UrbanImages = new HashSet<UrbanImage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int User_id { get; set; }
        public int Address_Id { get; set; }
        public string Investor { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Address_Details { get; set; }
        public string Description { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> PropertyCount { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Legal { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrbanAttribute> UrbanAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrbanImage> UrbanImages { get; set; }
    }
}
